### ISSUE TITLE
Last Pour Reporting in Gallons instead of Ounces

### ISSUE THREAD

**Issue by Tyfosho** [JohNan/home-assistant-plaato#4]
After setting up the Plaato Keg integration, the Last Pour entity is showing that the dispensed amount was gallons when it was actually ounces.

https://imgur.com/a/9xLe7lR

**Comment by JohNan** [comment]
hi @Tyfosho and thanks for reporting the issue.

By reading the docs I might have to add pin `v46` also to get the correct unit on last pour. See here: https://plaato.zendesk.com/hc/en-us/articles/360011259917-Pins-Plaato-Keg

Unfortunately I'm not able to try it since I don't own a Keg myself. If you are willing to share your `token` I might be able to add it. Let me know how you want to do and we can work out a safe way to share it.

**Comment by waltlillyman** [comment]
@JohNan I'm willing to share one of my active Plaato Keg tokens with you, if it will help your development efforts.

**Comment by Tyfosho** [comment]
Hi @JohNan, thanks for looking into this. I've also been wanting to dip my toes into Hassio Integration/add-on dev, so I'm willing to attempt to make the change and test it myself and submit a pull request if you're willing to give me a brief summary of the project structure.

**Comment by JohNan** [comment]
You can send me the token to <johan.nanzen+gh@gmail.com> and I'll see what I can do.

@Tyfosho the code for connecting to the api is in a separate python module that you can find here:  https://github.com/JohNan/pyplaato

The code should be pretty self-explanatory. There's a cli.py file that can be run from the command line so that you can test what values you receive. Each value is called a pin with a specific number. These can be found in the docs I linked to previously.

**Comment by waltlillyman** [comment]
Token sent.

**Comment by JohNan** [comment]
> Token sent.

Thank you. Token received.

**Comment by JohNan** [comment]
should be fixed in https://github.com/JohNan/home-assistant-plaato/releases/tag/v1.2.3
